image: golang:latest

variables:
  
  REPO_NAME: depot.dinf.usherbrooke.ca/dinf/projets/a20/eq05-gamesapi

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME/src


stages:
  - build
  - test
  - deploy


compile:
  stage: build
  script:
    - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/mybinary
  artifacts:
    paths:
      - mybinary

testing:
  stage: test
  script:
    - cd ..
    - cd $GOPATH/src/$REPO_NAME/tests/unit/controllers
    - go test
    - cd ..
    - cd $GOPATH/src/$REPO_NAME/tests/unit/domain
    - go test