#%RAML 1.0
traits:
  isLogin:
    headers:
      Authorization:
        displayName: Authorization
        description: Chaine de charactères de format `email;password`
        type: string
        required: true
    responses:
      200:
        headers:
          Authorization:
            displayName: Authorization
            description: Chaine de charactères contenant le token de session
            type: string
  hasRestrictedAccess:
    headers:
      Authorization:
        displayName: Authorization
        description: Token obtenu via un Login réussi. Valide pendant 10 minutes.
        type: bearer token
        required: true
    responses:
      403:
        body:
          application/json:
            description: erreur lors de l'accès à un chemin restreint
            type: string
            example: |
              {
                "Error" : "query rule violation: ensure 'userId' = '<nil>', instead got: ''"
              }
  hasAPIKey:
    headers:
      x-api-key:
        displayName: x-api-key
        description: Clé d'API obtenue auprès du support de GamesAPI
        type: string
        required: true
title: Game API
baseUri: "http://localhost:8080/"
/:
  displayName: Salutations
  get:
    is: [ hasAPIKey ]
    description: Salue l'usager
/auth:
  displayName: Authentification
  /login:
    post:
      is: [ hasAPIKey, isLogin ]
      description: Obtenir un token de session afin de s'authentifier lors des prochains appels à des chemins restreints.

/users:
  displayName: Usagers
  get:
    is: [ hasAPIKey, hasRestrictedAccess ]
    description: fetch tous les usagers
    responses:
      200:
        body:
          application/json:
            example: |
              [
                  {
                      "id": 1,
                      "created_at": "2020-12-02T19:17:33.7768138-05:00",
                      "updated_at": "2020-12-02T19:17:33.7768138-05:00",
                      "deleted_at": null,
                      "name": "master",
                      "email": "master@test.com",
                      "password_hash": "$2a$10$oT9RIIgxLsOPZZts7SEgV.2drgixOViVxRgRpQHfW6YeQYnDAriAC",
                      "steam_user_id": "nullid"
                  },
                  ...
              ]
  post:
    is: [ hasAPIKey, hasRestrictedAccess ]
    description: créer un usager
    body:
      application/json:
        example: |
          {
              "email":"dev2@test.com",
              "name":"dev2",
              "role":"admin",
              "password":"network7"
          }
    responses:
      201:
        body:
          application/json:
            example: |
              {
                  "id": 2,
                  "created_at": "2020-12-02T19:18:07.2384662-05:00",
                  "updated_at": "2020-12-02T19:18:07.2384662-05:00",
                  "deleted_at": null,
                  "name": "dev2",
                  "email": "dev2@test.com",
                  "password_hash": "$2a$10$neYZjTwKSxgNV9VIftEM4eqoyUD/XfnEMWH4q.KCKe7oVMiHBVRly",
                  "steam_user_id": "nullid"
              }
  /{id}:
    get:
      is: [ hasAPIKey, hasRestrictedAccess ]
      description: fetch un usager en particulier
    patch:
      is: [ hasAPIKey, hasRestrictedAccess ]
      description: MAJ un usager en particulier
    delete:
      is: [ hasAPIKey, hasRestrictedAccess ]
      description: supprimer un usager en particulier

/games:
  displayName: Jeux
  get:
    is: [ hasAPIKey, hasRestrictedAccess ]
  post:
    is: [ hasAPIKey, hasRestrictedAccess ]
  /{id}:
    get:
      is: [ hasAPIKey, hasRestrictedAccess ]
    patch:
      is: [ hasAPIKey, hasRestrictedAccess ]
    delete:
      is: [ hasAPIKey, hasRestrictedAccess ]
/LinkSteamUser:
  displayName: Associer un User ID Steam
  post:
    is: [ hasAPIKey, hasRestrictedAccess ]

/SyncGames:
  displayName: Synchronisation de jeux
  post:
    is: [ hasAPIKey, hasRestrictedAccess ]



